### ISSUE TITLE
LSM303 library throws error on ESP8266

### ISSUE THREAD

**Issue by gregwa1953** [mchobby/esp8266-upy#5]
I'm using Thonny as my IDE.
ESP8266 running MicroPython v1.18 on 2022-01-17; ESP module with ESP8266
Trying to run either of the three example programs all give the same result...

>>> %Run -c $EDITOR_CONTENT
Traceback (most recent call last):
  File "<stdin>", line 20, in <module>
  File "lsm303.py", line 250, in __init__
  File "lsm303.py", line 386, in _write_u8
OSError: [Errno 19] ENODEV
>>> 

Any suggestions?

**Comment by gregwa1953** [comment]
The wiring of the esp8266 is scl=Pin(5), sda=Pin(4)

The I2C addresses of the board are 0x19 and 0x1e

I've also tried this library on a Raspberry Pi Pico (using Micropython 1.17) and is fails at the same place.

**Comment by mchobby** [comment]
Hi, 
Your board is certainly configured to use the 0x1E address instead of the default one (0x1D).
**I just uploaded a new version of the lib** accepting the parameter address in the constructor (behind the i2c reference).
Just write `lsm= LSM303( i2c, address=0x1E )` instead of `lsm = LSM303( i2c )` ... it should work better.

**Comment by gregwa1953** [comment]
Thank you very much.

I'll give that a shot.
